ENH: pipeline function to make a topography periodic by mirroring
ComputationalMechanics/SurfaceTopography pull request #52
Opened 2020-12-08 13:50 UTC by AntoineSIMTEK

2020-12-18 08:41 UTC, pastewka requested changes
Looks good, just one minor comments. Also, some tests appear to fail.

2020-12-18 08:41 UTC, pastewka commented on SurfaceTopography/Uniform/Interpolation.py
> +Topography.register_function("mirror_stitch_periodize",
I would rename this to simply `mirror_stitch`.

2020-12-18 14:14 UTC, pastewka approved these changes

2021-01-15 13:13 UTC, AntoineSIMTEK commented
this branch fails because of problems with empty subdomains in muFFT. 

test_sphere with a communicator of length 4 is failing.

https://github.com/ComputationalMechanics/SurfaceTopography/pull/52/checks?check_run_id=1577117646

a fix is planned inside muFFT, correct @pastewka  ?

2021-02-02 10:21 UTC, pastewka commented
Let's see if this passes. Do you want to update the requirements to muFFT 0.13.0?

2021-02-02 10:26 UTC, AntoineSIMTEK commented
Actually besides of some number of MPI processes, the code is still compatible with the earlier muFFT. Only the test needs the newer  muFFT. 
So it depends what the philosphy behind "requirements" is.

2021-02-02 10:36 UTC, pastewka approved these changes

2021-02-02 11:33 UTC, merged